# The Basic Concepts of R
## Functions

**Function:** A body of reusable code used to perform specific tasks in R
They allow you to encapsulate code that you can execute by calling the function's name. Functions in R are essential for structuring your code and making it modular, allowing for easy reuse and debugging.

In [ ]:
# Defining a Function in R
add_numbers <- function(a, b) {
  sum <- a + b
  return(sum)
}

# Calling the function
result <- add_numbers(3, 5)
print(result)  # Output: 8


[1] 8


## Comments in Code

Comments are text notes in your code that are ignored by R during execution. They are used to explain what the code does, making it easier for others (or yourself) to understand the code later. In R, comments start with the `#` symbol.



In [ ]:
# This is a single-line comment explaining the code below
x <- 10  # Assigning the value 10 to the variable x
y <- 5   # Assigning the value 5 to the variable y
result <- x + y  # Adding x and y and assigning the result to

## Variables

Variables are used to store data or values that can be used and manipulated throughout your code. In R, you can assign values to variables using the `<-` operator, or the `=` operator.


In [ ]:
#----------
# Variables
#----------

# Assigning a numeric value to a variable
my_variable <- 25

# Assigning a string value to a variable
my_string <- "Hello, World!"

# Printing the variable values
print(my_variable)  # Output: 25
print(my_string)    # Output: Hello, World!


[1] 25
[1] "Hello, World!"


## Data Types

Data types define the kind of data that can be stored in a variable. Common data types in R include numeric, integer, character (strings), logical (TRUE or FALSE), and factors.


In [ ]:
#-----------
# Data Types
#-----------

# Numeric data type
num <- 42.5

# Integer data type
int <- 42L  # The 'L' denotes an integer

# Character (string) data type
char <- "R is fun!"

# Logical data type
bool <- TRUE

# Checking the data types
print(class(num))   # Output: "numeric"
print(class(int))   # Output: "integer"
print(class(char))  # Output: "character"
print(class(bool))  # Output: "logical"


[1] "numeric"
[1] "integer"
[1] "character"
[1] "logical"


## Conditional Statements (if)

### Single Condition

Conditional statements are used to execute code based on whether a condition is TRUE or FALSE. The `if` statement checks a single condition and runs the code block inside it if the condition is TRUE.


In [ ]:
#-----------------
# Single Condition
#-----------------

# Define variable
x <- 10
# if statement
if (x > 5) {
  print("x is greater than 5")
}

[1] "x is greater than 5"


Key Points:

* Single Condition: The if statement is used to check a single condition
* “TRUE” condition: The code inside the if block runs only when the condition is “TRUE”
* No Output for “FALSE”: If the condition is “FALSE”, the code inside the if block is skipped, and nothing happens

### Two Conditions (And, Or, and Not)

You can check multiple conditions in an `if` statement using logical operators:
- `&&` for AND (both conditions must be TRUE)
- `||` for OR (at least one condition must be TRUE)
- `!` for NOT (reverses the truth value of a condition)


In [ ]:
#------------------
# Two if conditions
#------------------

# Define variables
x <- 10
y <- 20

# if statement with AND clause
if (x > 5 && y < 30) {
  print("Both conditions are TRUE")
}

# if statement with OR clause
if (x > 15 || y < 30) {
  print("At least one condition is TRUE")
}

# if statement with Not clause
if (!(x > 15)) {
  print("x is not greater than 15")
}

[1] "Both conditions are TRUE"
[1] "At least one condition is TRUE"
[1] "x is not greater than 15"


### More than two conditions (else if)

The `else if` statement allows you to check additional conditions if the first `if` condition is FALSE. You can have multiple `else if` statements to check various conditions.



In [ ]:
#----------------------------
# More than two if conditions
#----------------------------

# Define variable
x <- 15

# if, else if and else statement
if (x < 10) {
  print("x is less than 10")
} else if (x < 20) {
  print("x is between 10 and 20")
} else {
  print("x is 20 or greater")
}

[1] "x is between 10 and 20"


To view another example that uses else if and logical operators select  
“Activity_2 - Simple Conditional Statement.”   https://github.com/Jake-Shiel/Learning-R
and  
“Conditional Statements with Logical Operators”   https://github.com/Jake-Shiel/Learning-R

### Nesting Statements

Nesting involves placing one `if` statement inside another `if` statement. They then evaluate expressions based on the conditions one by one, beginning from the outer condition to the inner one by one respectively.

To view a detailed commented example select: “Activity_3- Nested Conditional Statement”   
 https://github.com/Jake-Shiel/Learning-R


In [ ]:
#-------------------
# Nesting statements
#-------------------

# Define variables
x <- 15
y <- 5

# Nested if statement with an else clause
if (x > 10) {
  if (y < 10) {
    print("x is greater than 10 and y is less than 10")
  } else {
    print("x is greater than 10 and y is 10 or greater")
  }
}

[1] "x is greater than 10 and y is less than 10"


In [ ]:
#------------------------------------------------------------------------
# Check the age group and student status, then print a customized message
#------------------------------------------------------------------------

# Ask the user for their name
name <- readline(prompt = "Enter your name: ")

# Ask the user for their age and convert it to a numeric type
age <- as.numeric(readline(prompt = "Enter your age: "))

# Ask if the user is a student (Yes/No) and convert the response to logical
student_response <- readline(prompt = "Are you a student? (Yes/No): ")
is_student <- tolower(student_response) == "yes"

# If the user is under 18 years old
if (age < 18) {

  # Check if the user is a student
  if (is_student) {
    # If the user is a minor and a student, print this message
    print("You are a minor and a student.")
  } else {
    # If the user is a minor but not a student, print this message
    print("You are a minor and not a student.")
  }

  # If the user is between 18 and 64 years old (inclusive)
} else if (age >= 18 && age < 65) {

  # Check if the user is a student
  if (is_student) {
    # If the user is an adult and a student, print this message
    print("You are an adult and a student.")
  } else {
    # If the user is an adult but not a student, print this message
    print("You are an adult and not a student.")
  }

  # If the user is 65 years old or older
} else {

  # Check if the user is a student
  if (is_student) {
    # If the user is a senior and a student, print this message
    print("You are a senior and a student.")
  } else {
    # If the user is a senior but not a student, print this message
    print("You are a senior and not a student.")
  }
}

Enter your name: Jake
Enter your age: 26
Are you a student? (Yes/No): yes
[1] "You are an adult and a student."


## Loops

### For Loops

A `for` loop is used to repeat a block of code a certain number of times. It iterates over a sequence (like a vector) and executes the code block for each element in the sequence.



In [ ]:
#---------------------
# Print numbers 1 to 5
#---------------------

for (i in 1:5) {
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
#-------------------------------------------------
# Print square and square root of odd numbers 1:10
#-------------------------------------------------

# Define sequence
sequence_3 <- seq(from = 1, to = 10, by =2)
# For loop to iterate over all number in the sequence, calculates the square of each
# number and the square root then adds both to a print statement
for (i in sequence_3) {
  print(paste("The square of", i, "is", i*i,"and the square root is", i^(1/2)))
}

# Same outcome as above but the code written more explicitly:
for (i in sequence_3) {
  # Define a variable for each square and square root
  square <- i*i
  square_root <- i^(1/2)
  # Call the variable within the print rather than doing a calculation
  print(paste("The square of", i, "is", square,"and the square root is", square_root))
}

[1] "The square of 1 is 1 and the square root is 1"
[1] "The square of 3 is 9 and the square root is 1.73205080756888"
[1] "The square of 5 is 25 and the square root is 2.23606797749979"
[1] "The square of 7 is 49 and the square root is 2.64575131106459"
[1] "The square of 9 is 81 and the square root is 3"
[1] "The square of 1 is 1 and the square root is 1"
[1] "The square of 3 is 9 and the square root is 1.73205080756888"
[1] "The square of 5 is 25 and the square root is 2.23606797749979"
[1] "The square of 7 is 49 and the square root is 2.64575131106459"
[1] "The square of 9 is 81 and the square root is 3"


#### Break Statement

The `break` statement is used inside loops to exit the loop prematurely when a specific condition is met.



In [ ]:
#----------------
# Break statement
#----------------

# Stop the loop when i reaches 3
for (i in 1:5) {
  if (i == 3) {
    break   # Exit the loop when i is 3
  }
  print(i)
}

[1] 1
[1] 2


#### Next Statement

The `next` statement skips the current iteration of the loop and proceeds with the next iteration.


In [ ]:
#---------------
# Next statement
#---------------

# Loop through numbers 1 to 10 and skip even numbers
for (i in 1:10) {
  if (i %% 2 == 0) {
    next  # Skip the rest of the loop for even numbers
  }
  print(paste(i, "is odd"))
}

[1] "1 is odd"
[1] "3 is odd"
[1] "5 is odd"
[1] "7 is odd"
[1] "9 is odd"


### While Loops

A `while` loop repeats a block of code as long as a specified condition remains TRUE. The loop continues until the condition becomes FALSE.


In [ ]:
#----------------------------------------
# Print numbers 1 to 5 using a while loop
#----------------------------------------

i <- 1
while (i <= 5) {
  print(i)
  i <- i + 1  # Increment i by 1 each time
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
#----------------
# Basic countdown
#----------------

# Define the countdown variable
countdown <- 10
# While loop to check if countdown is more than zero
while (countdown > 0) {
  # Print current value
  print(countdown)
  # Decrease the countdown
  countdown <- countdown -1
}
# Print a message once the count down is done
print("Countdown complete")

[1] 10
[1] 9
[1] 8
[1] 7
[1] 6
[1] 5
[1] 4
[1] 3
[1] 2
[1] 1
[1] "Countdown complete"


In [ ]:
#------------------------------
# Calculate sum of even numbers
#------------------------------

# Initialize variables
current_number <- 1
sum_even <- 0

# While loop to sum even numbers between 1 and 20
while (current_number <= 20) {
  if (current_number %% 2 == 0) {
    sum_even <- sum_even + current_number
  }
  # Increment the current number
  current_number <- current_number + 1
}

# Print the result
print(paste("The sum of the even numbers from 1 to 20 is", sum_even))

[1] "The sum of the even numbers from 1 to 20 is 110"


## Data Structures
### Vectors
A vector is a basic data structure in R that holds elements of the same data type. Vectors can be created using the `c()` function, which combines values into a vector.
#### How to Create a Vector

In [ ]:
#------------------
# Creating a vector
#------------------

numeric_vector <- c(1, 2, 3, 4, 5)

#### Different Data Types within Vectors
Vectors in R can hold different types of data, but all elements in a vector must be of the same type. The common data types are:
* Numeric: Contains numbers.
* Character: Contains text strings.
* Logical: Contains boolean values (TRUE or FALSE).

The `typeof()` function is used to check the type of vector:

In [ ]:
#-------------------------------------------
# Creating vectors with different data types
#-------------------------------------------

# Creating a numeric(double) vector
numeric_vector <- c(1, 2, 3, 4, 5)

# Creating a character vector
char_vector <- c("apple", "banana", "cherry")

# Creating a logical vector
logical_vector <- c(TRUE, FALSE, TRUE)

# Print the vectors
print(typeof(numeric_vector))  # Output: "numeric"
print(numeric_vector)  # Output: 1 2 3 4 5
print(typeof(char_vector))  # Output: "character"
print(char_vector)     # Output: "apple" "banana" "cherry"
print(typeof(logical_vector))  # Output: "logical"
print(logical_vector)  # Output: TRUE FALSE TRUE

[1] "double"
[1] 1 2 3 4 5
[1] "character"
[1] "apple"  "banana" "cherry"
[1] "logical"
[1]  TRUE FALSE  TRUE


To create a vector of integers using the `c()` function, you must place the letter “L” after each number:


In [ ]:
 #---------------------------
 # Creating an Integer vector
 #---------------------------

integer_vector <- c(1L,2L,3L)

print(integer_vector)
print(typeof(integer_vector))

[1] "integer"


#### Indexing
Indexing in R allows you to access specific elements of a vector. R uses 1-based indexing, meaning the first element is accessed with the index 1.

In [ ]:
#---------
# Indexing
#---------

# Create a vector
fruit_vector <- c("apple", "banana", "cherry", "date")

# Access the first element
first_element <- fruit_vector[1]
print(first_element)  # Output: "apple"

# Access the third element
third_element <- fruit_vector[3]
print(third_element)  # Output: "cherry"

# Access multiple elements
subset_vector <- fruit_vector[c(2, 4)]
print(subset_vector)  # Output: "banana" "date"

[1] "apple"
[1] "cherry"
[1] "banana" "date"  


#### Operations with Vectors
You can perform various operations on vectors, such as adding them together or adding a constant to each element.

In [ ]:
#------------------------
# Operations with vectors
#------------------------

# Create numeric vectors
vector1 <- c(1, 2, 3)
vector2 <- c(4, 5, 6)

# Summing vectors
sum_vector <- vector1 + vector2
print(sum_vector)  # Output: 5 7 9

# Adding a number to each element
increment_vector <- vector1 + 10
print(increment_vector)  # Output: 11 12 13


[1] 5 7 9
[1] 11 12 13


#### Length of Vectors
The `length()` function determines the length of a vector. This function returns the number of elements in the vector.

In [ ]:
#------------------
# Length of Vectors
#------------------

# Using the vector from the previous example
print(vector1)
length(vector1)

# Longer vector to demonstrate
vector3 <- c(1, 2, 3, 4, 5, 6)
print(vector3)
length(vector3)


[1] 1 2 3


[1] 3

### Lists
#### Creating a List
A list is a data structure in R that can contain elements of different data types. This makes it more flexible than a vector.

In [ ]:
#----------------
# Creating a list
#----------------

# Creating a list with different data types
my_list <- list(42, "apple", TRUE, c(1, 2, 3))

# Print the list
print(my_list)

[[1]]
[1] 42

[[2]]
[1] "apple"

[[3]]
[1] TRUE

[[4]]
[1] 1 2 3



#### Accessing Elements in a List
You can access elements in a list using double square brackets `[[]]` for individual elements, or single brackets `[]` for sublists.

In [ ]:
#-----------------------------
# Accessing elements in a list
#-----------------------------

# Accessing the first element (a number)
first_element <- my_list[[1]]
print(first_element)  # Output: 42

# Accessing the second element (a string)
second_element <- my_list[[2]]
print(second_element)  # Output: "apple"

# Accessing the fourth element (a vector)
fourth_element <- my_list[[4]]
print(fourth_element)  # Output: 1 2 3

[1] 42
[1] "apple"
[1] 1 2 3


### Data Frames
#### Creating a Data Frame
A data frame is a table-like structure in R where each column can contain different types of data (numeric, character, etc.). It's commonly used for storing datasets.

In [ ]:
#----------------------
# Creating a data frame
#----------------------

df <- data.frame(
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(25, 30, 35),
  Height = c(5.5, 6.0, 5.8)
)

# Print the data frame
print(df)

     Name Age Height
1   Alice  25    5.5
2     Bob  30    6.0
3 Charlie  35    5.8


#### Accessing a Data Frame
You can access data in a data frame by row or by column.

In [ ]:
#-----------------------
# Accessing a data frame
#-----------------------

# Accessing a column by name
age_column <- df$Age
print(age_column)
# Output: 25 30 35

# Accessing a specific row
first_row <- df[1, ]
print(first_row)
# Output: Name Age Height
#         1 Alice  25    5.5

# Accessing a specific element (row 2, column 3)
element <- df[2, 3]
print(element)
# Output: 6


[1] 25 30 35
   Name Age Height
1 Alice  25    5.5
[1] 6


### Matrices
#### Creating a Matrix
A matrix is a two-dimensional data structure in R, where all elements must be of the same type.

In [ ]:
#----------------------
# Creating a 3x3 matrix
#----------------------

matrix_1 <- matrix(1:9, nrow = 3, ncol = 3)
print(matrix_1)
# Output:
#      [,1] [,2] [,3]
# [1,]    1    4    7
# [2,]    2    5    8
# [3,]    3    6    9


     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


#### Accessing a Matrix
You can access elements of a matrix using indices `[row, column]`.

In [ ]:
#-------------------
# Accessing a Matrix
#-------------------

# Accessing an element (row 2, column 3)
element <- matrix_1[2, 3]
print(element)  # Output: 8

# Accessing an entire row
row <- matrix_1[1, ]
print(row)  # Output: 1 4 7

# Accessing an entire column
column <- matrix_1[, 2]
print(column)  # Output: 4 5 6


[1] 8
[1] 1 4 7
[1] 4 5 6


#### Matrix Operations
You can perform operations like element-wise addition or multiplication on matrices, as well as matrix multiplication.

In [ ]:
#------------------
# Matrix Operations
#------------------

# Creating another matrix
matrix_2 <- matrix(9:1, nrow = 3, ncol = 3)

# Element-wise addition
sum_matrix <- matrix_1 + matrix_2
print(sum_matrix)
# Output:
#      [,1] [,2] [,3]
# [1,]   10   10   10
# [2,]   10   10   10
# [3,]   10   10   10

# Element-wise multiplication
prod_matrix <- matrix_1 * matrix_2
print(prod_matrix)
# Output:
#      [,1] [,2] [,3]
# [1,]    9   32   63
# [2,]   16   25   48
# [3,]   21   36   27

# Matrix multiplication
mult_matrix <- matrix_1 %*% matrix_2
print(mult_matrix)
# Output:
#      [,1] [,2] [,3]
# [1,]   42   48   54
# [2,]   78   93  108
# [3,]  114  138  162


     [,1] [,2] [,3]
[1,]   10   10   10
[2,]   10   10   10
[3,]   10   10   10
     [,1] [,2] [,3]
[1,]    9   24   21
[2,]   16   25   16
[3,]   21   24    9
     [,1] [,2] [,3]
[1,]   90   54   18
[2,]  114   69   24
[3,]  138   84   30


### Factors
#### Handling Categorical Data
Factors are used to handle categorical data in R. They store both the values and their levels (categories).

#### Creating a Factor for Categorical Variable
You can create a factor by using the factor() function.

In [ ]:
#------------------
# Creating a Factor
#------------------

# Creating a factor for a categorical variable
gender <- factor(c("Male", "Female", "Female", "Male", "Male"))
print(gender)
# Output: [1] Male   Female Female Male   Male
# Levels: Female Male


[1] Male   Female Female Male   Male  
Levels: Female Male


#### Levels
Levels are the distinct categories in a factor. You can check the levels of a factor using the `levels()` function

In [ ]:
#----------------
# Checking levels
#----------------

levels(gender)
# Output: 'Female''Male'

[1] "Female" "Male"

#### Converting to Factor
In R, converting a character vector to a factor involves changing the representation of the data from a simple string format to a more structured categorical format.

In [ ]:
#----------------------------------
# Convert Charcter Vector to Factor
#----------------------------------

days <- factor(c("Monday", "Tuesday", "Wednesday"))
print(days)

[1] Monday    Tuesday   Wednesday
Levels: Monday Tuesday Wednesday
